source 'https://rubygems.org'

gem 'em-mqtt'
gem 'activesupport'
gem 'rest-client'
gem 'foreman'
gem 'ruby-sun-times'
gem 'em-websocket'
gem 'rspec'
gem 'timecop'
gem 'thin'
gem 'rack'
gem 'rack-rewrite'
gem 'mysql2'
gem 'em-serialport', :git => 'https://github.com/BobTheBotMaker/em-serialport.git'
#gem 'nokogiri'
