lat: 52.0263009
lng: 5.5544309
mqtt_url: '127.0.0.1'
database:
  host: localhost
  user: root
  port: 3306
  database: home_development
components:
  webserver:
    port: 8085

  train:
    user: <%= ENV['NS_API_USER'] %>
    password: <%= ENV['NS_API_PASS'] %>
    station: 'klp'

  lifx:
    api_key: <%= ENV['LIFX_API_KEY'] %>
    entities:
      living:
        name: 'Living room'
        icon: 'i-lightbulb-o'
        code: 'group:Living'
      all:
        name: 'All'
        icon: 'i-lightbulb-o'
        code: 'all'

  kaku:
    tv:
      name: 'TV woonkamer'
      icon: 'desktop'
      code: 'M 14'
    computer:
      name: 'Computer'
      icon: 'i-lightbulb-o'
      code: 'M 18'
    bedroom_all:
      name: 'Bedroom All'
      icon: 'i-lightbulb-o'
      code: 'M 16'

  blokker:
    kitchen:
      name: 'Kitchen'
      icon: 'i-lightbulb-o'
      code: '1'
    christmas_lights:
      name: 'Christmas lights'
      code: '2'

  group:
    all:
      name: 'All'
      members:
        - 'group/living'
        - 'group/bedroom'

    living:
      name: 'Living room'
      members:
        - 'kaku/tv'
        - 'kaku/computer'
        - 'blokker/kitchen'
        - 'blokker/christmas_lights'
        - 'lifx/living'

    bedroom:
      name: 'Bedroom'
      members:
        - 'kaku/bedroom_all'

  metric:
    water:
      key: 'w'
      listen: 'metrics/water'
      formatter: 'water'

    electricity:
      key: 'e'
      listen: 'metrics/electricity'
      formatter: 'electricity'

    gas:
      key: 'g'
      listen: 'metrics/gas'
      formatter: 'gas'

  scene:
    sunset_start:
      description: "Start sunset"
      visible: false
      actions:
        -
          component: 'lifx/living/on'
          params:
            brightness: 80
            duration: 60

    sunset_end:
      description: "End sunset"
      visible: false
      actions:
        -
          component: 'lifx/living/on'
          params:
            brightness: 90
            duration: 10
    bed:
      description: "Bed"
      actions:
        -
          component: 'group/living/off'
          params:
            duration: 60
        -
          component: 'group/bedroom/on'

    sleep:
      description: "Sleep"
      actions:
        -
          component: 'group/bedroom/off'
          params:
            duration: 60
        -
          component: 'group/living/off'
          params:
            duration: 60

    morning:
      description: "Morning"
      actions:
        -
          component: 'group/bedroom/off'
        -
          component: 'kaku/computer/on'
        -
          component: 'blokker/kitchen/on'
        -
          component: 'lifx/living/on'
          params:
            duration: 60
            brightness: 80
            color: kelvin:3500

    early_night:
      description: "Early night (22:00)"
      actions:
        -
          component: 'lifx/living/update'
          params:
            brightness: 20
            duration: 7200
            color: 'kelvin:2500'

    late_night:
      description: "Late night (23:00)"
      actions:
        -
          component: 'lifx/living/update'
          params:
            brightness: 10
            duration: 1800
            color: 'orange'
        -
          component: 'blokker/kitchen/off'
        -
          component: 'blokker/christmas_lights/off'
        -
          component: 'kaku/tv/off'
    tv:
      actions:
        -
          component: 'kaku/tv/on'
        -
          component: 'lifx/living/on'
          params:
            brightness: 40
            duration: 10
            color: 'kelvin:2800'

  virtual:
    white_box_left:
      listen: 'components/buttonboxwhite/leftButton'
      actions:
        -
          component: 'scene/tv/trigger'
    white_box_middle:
      listen: 'components/buttonboxwhite/middleButton'
      actions:
        -
          component: 'scene/bed/trigger'
    white_box_right:
      listen: 'components/buttonboxwhite/rightButton'
      actions:
        -
          component: 'scene/sleep/trigger'

  automate:
    sunset_start:
      description: "When sun sets, slowly fade on the lights"
      triggers:
        -
          type: event
          event: 'sun/sunset_start'
      actions:
        -
          component: 'scene/sunset_start/trigger'

    sunset_end:
      description: "When sunset ends, switch on the rest of the lights"
      triggers:
        -
          type: event
          event: 'sun/sunset_end'
      actions:
        -
          component: 'scene/sunset_end/trigger'

    early_night:
      description: "At 22:00 in the eventing, start fading the lights"
      triggers:
        -
          type: timer
          time: '22:00'

      actions:
        -
          component: 'scene/early_night/trigger'

    late_night:
      description: "At 23:00, fade the lights even more"
      triggers:
        -
          type: timer
          time: '23:00'

      actions:
        -
          component: 'scene/late_night/trigger'
