lat: 52.0263009
lng: 5.5544309
components:
  lifx:
    api_key: <%= ENV['LIFX_API_KEY'] %>
    entities:
      living:
        name: 'Living room'
        icon: 'i-lightbulb-o'
        code: 'group:Living'
      all:
        name: 'All'
        icon: 'i-lightbulb-o'
        code: 'all'

  monitor:
    active: true

  kaku:
    living:
      name: 'TV woonkamer'
      icon: 'desktop'
      code: 'M 16'
    christmas:
      name: 'Kerstverlichting'
      icon: 'i-lightbulb-o'
      code: 'M 16'

  group:
    group1:
      name: 'All'
      members:
        - 'kaku/living'
        - 'kaku/christmas'
        - 'lifx/living'
