lat: 52.0263009
lng: 5.5544309
components:
  lifx:
    api_key: <%= ENV['LIFX_API_KEY'] %>
    entities:
      living:
        name: 'Living room'
        icon: 'i-lightbulb-o'
        code: 'group:Living'
      all:
        name: 'All'
        icon: 'i-lightbulb-o'
        code: 'all'

  monitor:
    active: true

  kaku:
    living:
      name: 'TV woonkamer'
      icon: 'desktop'
      code: 'M 16'
    christmas:
      name: 'Kerstverlichting'
      icon: 'i-lightbulb-o'
      code: 'M 16'

  group:
    all:
      name: 'All'
      members:
        - 'kaku/living'
        - 'kaku/christmas'
        - 'lifx/living'
    living:
      name: 'Living room'
      members:
        - 'kaku/living'
        - 'kaku/christmas'
        - 'lifx/living'

    bedroom:
      name: 'Bedroom'
      members:
        - 'blokker/nightstand'

  scene:
    sunset:
      members:
        -
          component: 'lifx/living/on'
          params:
            brightness: 80
            duration: 60
    bed:
      members:
        -
          component: 'group/living/off'
          params:
            duration: 60
        -
          component: 'group/bedroom/on'

automate:
  sunset:
    trigger:
      type: state
      component: sun
      field: next_sunset
      offset:
        hours: -1
    actions:
      -
        component: 'scene/sunset/trigger'
